language: crystal
script:
- crystal spec
- crystal docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  project_name: YOUR-GITHUB-REPOSITORY-NAME
  on:
    branch: master
  local_dir: doc